#!/bin/bash
# Part B Scripting Requirement 1
# Written by Brian Nguyen s3689020
# This script will display one of the following
# 1. Amount of free and occupied memory.
# 2. Amount of disk space occupied and free on system.
# 3. Connection info for each network connection onf system.
# 4. Amount of time system has been running.

if [ $1 == 'mem' ]
then
  free -m -h  # provides info on memory
elif [ $1 == 'disk' ]
then
  df -h  # provides disk free space occupied
elif [ $1 == 'con' ]
then
  ifconfig  # provides connection information
elif [ $1 == 'time' ]
then
  uptime  # provides system running uptime
else
  echo "Error! please enter a valid argument."  # error message if user enter invalid argument
fi
