#!/bin/bash
# This is the Menu System for Part C of the assignment written by Brian Nguyen s3689020

PRINTF=/usr/bin/printf
LS=/bin/ls

PWD=/bin/pwd
SLEEP=/bin/sleep
QUIT=0
menu(){
  $CLEAR
  $PRINTF "\n"
  $PRINTF "~~~~~~~~~~~~~~~~~~~~\n"
  $PRINTF " User Menu System\n"
  $PRINTF "~~~~~~~~~~~~~~~~~~~~"
  $PRINTF "\n"
  $PRINTF " 1) Display basic information \n"
  $PRINTF "\n"
  $PRINTF " 2) Display basic information (Items that involve post-processing) \n"
  $PRINTF "\n" 
  $PRINTF " 3) Find an item within system and apply an action (delete/print/print0/custom) \n"
  $PRINTF "\n"
  $PRINTF " 4) Basic profiler of the program you want \n"
  $PRINTF "\n"
  $PRINTF "Please enter [1-4] for the any of the options above, or Q to quit the menu:"
  
  return
}


# Set up input validation and menu for Basic information display (Part B Req1)
display1_cases(){
  local QUITDISPLAY=0
  while [ $QUITDISPLAY -eq 0 ] ; do
  $PRINTF "What basic information would you like to display? Enter one of (mem/disk/con/time), or enter Q to quit \n"
  read -r CHOICE
  if [ "$CHOICE" == "mem" ] || [ "$CHOICE" == "disk" ] || [ "$CHOICE" == "con" ] || [ "$CHOICE" == "time" ]; then
    ./display1 "$CHOICE"
    $PRINTF "\n"
  elif [ "$CHOICE" == "Q" ] || [ "$CHOICE" == "q" ]; then
    QUITDISPLAY=1
  else echo "Invalid option, please enter either mem/disk/con/time for display info or Q to quit display function\n"
  fi
done
}


# Set up input validation and menu for Basic information display with processing (Part B Req2)
display2_cases(){
  local QUITDISPLAY=0
  while [ $QUITDISPLAY -eq 0 ] ; do
  $PRINTF "What basic information with post processing would you like to display?\n"
  $PRINTF "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
  $PRINTF "Please enter options as a combination of [ncpfo] where:\n"
  $PRINTF "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
  $PRINTF "n gives the number of CPU core on the system\n"
  $PRINTF "c gives currenct process' priority\n"
  $PRINTF "p gives the total number of processes running under current user\n"
  $PRINTF "f gives the number of open file descriptors owned by the current user\n"
  $PRINTF "o gives the max number of file descriptors that can be opened by a process\n"
  $PRINTF "or enter Q to quit \n"
  $PRINTF "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
  read -r CHOICE
  if ! [[ "$CHOICE" =~ [^ncpfo] ]]; then
    $PRINTF "\n"
    ./display2 "-$CHOICE"
    $PRINTF "\n"
  elif [ "$CHOICE" == "Q" ] || [ "$CHOICE" == "q" ]; then
    QUITDISPLAY=1
  else 
    $PRINTF "\n"
    echo "Invalid option, please enter either options as a combination of [ncpfo] for display info or Q to quit display function"
    $PRINTF "\n"
  fi
done
}


while [ $QUIT -eq 0 ] ; do
  menu

  read -r CHOICE
  case $CHOICE in
    1)
      $PRINTF "\n"
      $PRINTF "\n"
      display1_cases
      $PRINTF "\n"
      $SLEEP 2
      ;;
    2)
      $PRINTF "\n"
      $PRINTF "\n"
      display2_cases
      $PRINTF "\n"
      $SLEEP 2
      ;;
    3)
      $PRINTF "\n"
      $PRINTF "\n"
      $LS
      $SLEEP 2
      ;;
    4)
      $PRINTF "\n"
      $PRINTF "\n"
      $PRINTF "And that's goodnight from me\n"
      $SLEEP 2
      ;;
    [Qq])
      QUIT=1;;
    ?)
      $PRINTF "\n"
      $PRINTF "\n"
      $PRINTF "Invalid option entered\n"
      $PRINTF "Valid options are 1, 2, 3, 4, and Q to quit\n"
      $SLEEP 2;;
  esac
done      
